name: Build and publish artifacts

on:
  release:
    types: [published]

jobs:
  build_and_upload_binaries:
    strategy:
      matrix:
        debug: ["", "--debug"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Build ts
      run: make clean build

    - name: Store current tag
      run: echo "GIT_TAG=`git tag --points-at HEAD`" >> $GITHUB_ENV

    # Note: this only creates builds on the platform being built. So
    # this does not build for M1 Macs. Maybe in the future we could
    # use Zig's cross-platform builds instead of relying on the
    # current platform and different Github Actions runners.
    - name: Create zip of release build
      run: zip -9 ts-$RUNNER_OS-x64-$GIT_TAG${{ matrix.debug }}.zip ts

    - name: Get Github ID for tag
      run: |
        echo "RELEASE_ID=`curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/bermi/ts/releases/tags/$GIT_TAG | jq '.id'`" >> $GITHUB_ENV
    - name: Upload on release
      run: |
        curl --fail \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @./ts-$RUNNER_OS-x64-$GIT_TAG${{ matrix.debug }}.zip \
          "https://uploads.github.com/repos/bermi/ts/releases/$RELEASE_ID/assets?name=ts-$RUNNER_OS-x64-$GIT_TAG${{ matrix.debug }}.zip"
